# -*- coding: utf-8 -*-
"""yolo recorded video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhafXYKPNB2PKQnLnvKs1NJs8533aU7H
"""

!pip install ultralytics -q

!yolo detect predict model=yolov8m.pt source="/content/cars.mp4"

!ffmpeg -i {"/content/runs/detect/predict/cars.avi"} -vcodec libx264 {"final.mp4"}